# 是否保存图片
save: true
# 是否使用已保存的图片作为缓存
cache: false
# 是否提示Get和Adv命令已受理
notify: true
# 是否发送图片信息
verbose: true
# 图片发送模式: Simple/Flash/Forward
messageType: Simple
# 图片大小: Original/Regular/Small/Thumb/Mini
size: Regular
# 获取Pixiv图片的反向代理
proxy: 'https://i.pixiv.re'
# 默认的撤回时间(单位：s)
recall: 30
# 是否撤回图片信息
recallImgInfo: false
# 是否撤回图片
recallImg: false
# 默认的冷却时间(单位：s)
cooldown: 5
# 标签过滤模式: None/Whitelist/Blacklist
tagFilterMode: None
# 标签过滤器，白名单模式只发送包含指定标签的图片，黑名单模式只发送不包含指定标签的图片。(仅Get命令，Adv命令中不生效)
tagFilter: []