# API返回了错误
invokeException: API调用错误，请检查日志
# 没有找到相关图片
emptyImageData: 没有找到相关图片, 换个关键词试试吧
# 指令未冷却
inCooldown: 你怎么冲得到处都是
# 标签被过滤
filteredTag: 该图片标签已被过滤，请换个标签再试
# 获取图片失败
networkError: '网络连接失败/超时或图片已被删除，之后再试试吧'
# JSON格式错误
invalidJson: JSON格式错误
# 没有群主和管理员权限
nonAdminPermissionDenied: 该命令仅限群主和管理员使用
# 非受信任的用户
untrusted: 非受信任的用户不能设置该属性, 让Bot所有者添加到受信任用户名单后才能使用
# set命令执行成功
setSucceeded: 设置成功
# 非法值
illegalValue: 不是有效的数字
# 提示Get和Adv命令已受理
notify: 正在获取图片...